### ISSUE TITLE
Почта

### ISSUE THREAD

**Issue by sh779lex** [Noob-Coder-s/WebSite#10]
Нам нужен почтовый ящик на домене

**Comment by sh779lex** [comment]
Обещал заняться ззноб

**Comment by zznobzz** [comment]
Варианты, где хостить  почту:
* Яндекс- платно,
* Mail.RU - кажется бесплатно, надо проверять.
* Предлагайте варианты............

**Comment by sh779lex** [comment]
> Варианты, где хостить почту:
> 
> * Яндекс- платно,
> * Mail.RU - кажется бесплатно, надо проверять.
> * Предлагайте варианты............

А на cloudflare не получилось?

**Comment by zznobzz** [comment]
Cloudflare  не предоставляет услуги почты для домена. Если за Яндекс, то 299₽/мес за пользователя.
Мэйл, бесплатно, но с рекламой.
