### ISSUE TITLE
Фавикон

### ISSUE THREAD

**Issue by sh779lex** [Noob-Coder-s/WebSite#6]
Он отсутствует, нужно решить какой выбрать и разместить

**Comment by navferty** [comment]
Добавил фавикон, сконвертированный из [лого](https://noobcoders.ru/img/logo.svg)https://[noobcoders.ru/img/logo.svg](https://noobcoders.ru/img/logo.svg)

**Comment by sh779lex** [comment]
У меня фавикон не отображается
